dropdown_configurations:
  type: list
  default: ""
  description: |
    Configure custom dropdowns for Data Explorer queries. Each line represents one configuration.
    Format: queryId|paramName|label1:value1,label2:value2,...
    
    Example:
    12|parent_category_name|Access Analyzer:access-analyzer,Account:account,Billing:billing
  list_type: compact

target_query_id:
  type: integer
  default: 0
  description: "The ID of the Data Explorer query where you want to hide a parameter"

parameter_to_hide:
  type: string
  default: ""
  description: "The name of the parameter field you want to hide (e.g. parent_category_name)"