dropdown_configurations:
  type: list
  default: ""
  description: |
    Configure custom dropdowns for Data Explorer queries. Each line represents one configuration.
    Format: queryId|paramName|label1:value1,label2:value2,...
    
    Example:
    12|parent_category_name|Access Analyzer:access-analyzer,Account:account,Billing:billing
  list_type: compact